#### Week 4 Assignment
**1.** What are the key steps of a data cleaning pipeline? State why each step is important and what would be the consequence of missing that step.  10 points 

Steps:
*1. Drop Unwanted Features*: This is necessary to drop features that aren't trivial to the goal of the project/assignment and wouldn't affect any outcomes that are needed. Missing this step would cause data results to be skewed, which could result in incorrect data being shown and evaluated. This could cost a business lots of money with incorrect data.

*2. Address Missing Values*: Missing values need to be address in order to not report unfinished or unknown data, which may also skew the data. This is important because null or empty values will clutter the data and skew outcomes. 

*3. Remove Duplicates*: Removing duplicates is needed to not report on the same instance multiple times, as this may result in incorrect results when evaluating the data. These need to be removed in order for each datapoint to be unique in the database. 

*4. Fix Structural Errors (Features w/ Wrong Data Types)*: This is necessary in order to use the feature to evaluate the data. For example, an entry that is a string where it is supposed to be an int will cause errors further on, and may cause difficulty in pinpointing the issue when the error occurs. It is also essential to create uniformity in reporting the data, and in cases where the data needs to be translated into a different format, such as from database to boxplot.

*5. Check Valid Inputs for Categorical Features*: This is necessary to ensure that all data is uniform and can be used easily, rather than worrying about different formats for data in the same category. For example, string data being in both lowercase and uppercase may cause later errors.

*6. Identify Numerical Outliers*: Identifying outliers is needed to evaluate normalities within the data and can be used to identify causes for outlier cases. It is also necessary so that the data within the normal range isn't skewed based on these outliers, since they are special cases.

**2 Take an overview of the dataset.    5 points**
(note: must upload the file in jupyter after downloading it)

In [29]:
import pandas as pd
df = pd.read_csv('webautomation_coursera.csv')
df.shape
index = df.columns.tolist()
index

['url',
 'title',
 'associated-university-institution-company',
 'type',
 'image',
 'category-subject-area',
 'certificate-is-available',
 'description',
 'duration',
 'language',
 'level',
 'prerequisites',
 'price',
 'rating',
 'syllabus',
 'timestamp']

**3. Remove these features that are not used in this project,  ‘image’, ‘description’, ‘prerequisites’, ‘syllabus‘’.     5 points**

In [30]:
removelist = ['image', 'description', 'prerequisites', 'syllabus']
df.drop(removelist, inplace=True, axis=1)
df.columns.tolist()

['url',
 'title',
 'associated-university-institution-company',
 'type',
 'category-subject-area',
 'certificate-is-available',
 'duration',
 'language',
 'level',
 'price',
 'rating',
 'timestamp']

**4. How many values are missing in each of the remained features? What percentage of data is missing in each feature?  -no need to explain the result.   10 points**

In [31]:
df.isnull().sum()

url                                           0
title                                         3
associated-university-institution-company    19
type                                          1
category-subject-area                         4
certificate-is-available                     24
duration                                     20
language                                     20
level                                        55
price                                        20
rating                                       21
timestamp                                     0
dtype: int64

In [32]:
import numpy as np
for cols in df.columns:
    pct_missing = (df[cols].isnull().sum())/df.shape[0]
    print(cols, round(pct_missing, 2))

url 0.0
title 0.01
associated-university-institution-company 0.08
type 0.0
category-subject-area 0.02
certificate-is-available 0.1
duration 0.08
language 0.08
level 0.23
price 0.08
rating 0.09
timestamp 0.0

**5. Replace it with ‘English’ where the value for the column ‘language’ is missing. Delete the row where If the value for the column ‘rating’ is missing. Delete the rows that still have more than 3 values missing across the columns.    10 points**

In [33]:
df.shape
df['language'].fillna('English', inplace=True)
df_new = df.dropna(axis=0, subset=['rating'])
df_new_new = df_new.dropna(axis=0, thresh=9)
df_new_new.isnull().sum()

url                                           0
title                                         0
associated-university-institution-company    15
type                                          0
category-subject-area                         0
certificate-is-available                      4
duration                                      0
language                                      0
level                                        34
price                                         0
rating                                        0
timestamp                                     0
dtype: int64

**6. This data has no IDs, but we can use the ‘url’ as the keys. Each course shall have a unique link. Check if there are duplicates in the column ‘url’. If there are duplicates, keep the last row. Compare the shape of the DataFrame before and after the deduplication, how many duplicates were removed?    10 points**

In [34]:
df_new_new.shape

(220, 12)

In [35]:
df_new_nodups = df_new_new.drop_duplicates(subset=['url'], keep='last')
df_new_nodups.shape

(167, 12)

**7. Check the data type of the column ‘timestamp’. Is this an object or a datetime? If it is an object, change this column to a datetime.  5 points**

In [36]:
print(df_new_nodups['timestamp'].dtype)

object

In [37]:
df_new_nodups['timestamp_dt'] = pd.to_datetime(df_new_nodups['timestamp'], format='%Y-%m-%d')
print(df_new_nodups['timestamp_dt'].dtype)

datetime64[ns, UTC]

C:\Users\mcken\AppData\Local\Temp\ipykernel_7840\3333747388.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new_nodups['timestamp_dt'] = pd.to_datetime(df_new_nodups['timestamp'], format='%Y-%m-%d')

**8. Change the column name ‘associated-university-institution-company’ to ‘institution’. Check the values in each of the two categorical features, ‘institution’ and ‘type’. Are there any inconsistencies in these categorical attributes? For example, ‘Google Cloud’ and ‘Google’ shall be merged into ‘Google’. 10 points**

In [38]:
df_renamed = df_new_nodups.rename(columns={'associated-university-institution-company':'institution'})
df_renamed.columns.tolist()

['url',
 'title',
 'institution',
 'type',
 'category-subject-area',
 'certificate-is-available',
 'duration',
 'language',
 'level',
 'price',
 'rating',
 'timestamp',
 'timestamp_dt']

In [39]:
df_renamed.head(50)

,url,title,institution,type,category-subject-area,certificate-is-available,duration,language,level,price,rating,timestamp,timestamp_dt
1,https://www.coursera.org/learn/2NAspeedNAit,Two Speed IT: How Companies Can Surf the Digit...,CentraleSupélec,course,Business Essentials,Shareable Certificate,Approx. 14 hours to complete,English,NaN,free,4.3,2022-07-29T23:58:34Z,2022-07-29 23:58:34+00:00
2,https://www.coursera.org/learn/fundamentalsNAn...,Fundamentals of Network Communication,University of Colorado System,course,Computer Security and Networks,Shareable Certificate,Approx. 15 hours to complete,English,Intermediate Level,free,4.6,2022-07-29T23:58:54Z,2022-07-29 23:58:54+00:00
3,https://www.coursera.org/learn/uxNAdesignNAjobs,Design a User Experience for Social Good & Pre...,Google,course,Design and Product,Shareable Certificate,Approx. 71 hours to complete,English,Beginner Level,free,4.8,2022-07-29T23:59:20Z,2022-07-29 23:59:20+00:00
4,https://www.coursera.org/learn/databaseNAappli...,Building Database Applications in PHP,University of Michigan,course,Mobile and Web Development,Shareable Certificate,Approx. 24 hours to complete,English,Intermediate Level,free,4.9,2022-07-29T23:59:20Z,2022-07-29 23:59:20+00:00
5,https://www.coursera.org/learn/webNAdesignNAwi...,Web Design: Wireframes to Prototypes,California Institute of the Arts,course,Music and Art,Shareable Certificate,Approx. 41 hours to complete,English,Intermediate Level,free,4.9,2022-07-29T23:59:20Z,2022-07-29 23:59:20+00:00
6,https://www.coursera.org/learn/wireframesNAlow...,Build Wireframes and LowNAFidelity Prototypes,Google,course,Design and Product,Shareable Certificate,Approx. 22 hours to complete,English,Beginner Level,free,4.9,2022-07-29T23:59:51Z,2022-07-29 23:59:51+00:00
7,https://www.coursera.org/learn/introductionNAp...,Introduction to C# Programming and Unity,University of Colorado System,course,Software Development,Shareable Certificate,Approx. 19 hours to complete,English,Beginner Level,free,4.6,2022-07-30T00:00:07Z,2022-07-30 00:00:07+00:00
8,https://www.coursera.org/specializations/virtu...,Virtual Reality Specialization,NaN,specializations,Design and Product,Shareable Certificate,Approximately 6 months to complete,English,Beginner Level,free,4.7,2022-07-30T00:00:07Z,2022-07-30 00:00:07+00:00
9,https://www.coursera.org/specializations/cplus...,C++ Programming for Unreal Game Development Sp...,University of Colorado System,specializations,Software Development,Shareable Certificate,Approximately 4 months to complete,English,Intermediate Level,free,4.6,2022-07-30T00:00:07Z,2022-07-30 00:00:07+00:00
10,https://www.coursera.org/specializations/gameN...,Game Design and Development with Unity 2020 Sp...,Michigan State University,specializations,Software Development,Shareable Certificate,Approximately 5 months to complete,English,Beginner Level,free,4.8,2022-07-30T00:00:36Z,2022-07-30 00:00:36+00:00
12,https://www.coursera.org/specializations/uvaNA...,Digital Product Management Specialization,University of Virginia,specializations,Design and Product,Shareable Certificate,Approximately 5 months to complete,English,Beginner Level,free,4.8,2022-07-30T00:00:36Z,2022-07-30 00:00:36+00:00
13,https://www.coursera.org/specializations/webNA...,Web Design for Everybody: Basics of Web Develo...,University of Michigan,specializations,Mobile and Web Development,Shareable Certificate,Approximately 6 months to complete,English,Beginner Level,free,4.8,2022-07-30T00:01:22Z,2022-07-30 00:01:22+00:00
15,https://www.coursera.org/learn/foundationsNAus...,Foundations of User Experience (UX) Design,Google,course,Design and Product,Shareable Certificate,Approx. 18 hours to complete,English,Beginner Level,free,4.8,2022-07-30T00:01:22Z,2022-07-30 00:01:22+00:00
16,https://www.coursera.org/professionalNAcertifi...,Google UX Design Professional Certificate,Google,professional certificates,Design and Product,Shareable Certificate,Approximately 6 months to complete,English,Beginner Level,free,4.8,2022-07-30T00:02:16Z,2022-07-30 00:02:16+00:00
17,https://www.coursera.org/learn/fundamentalsNAo...,Fundamentals of Graphic Design,California Institute of the Arts,course,Music and Art,Shareable Certificate,Approx. 15 hours to complete,English,Beginner Level,free,4.8,2022-07-30T00:02:16Z,2022-07-30 00:02:16+00:00
18,https://www.coursera.org/learn/htmlNAcssNAjava...,"HTML, CSS, and Javascript for Web Developers",NaN,course,Mobile and Web Development,Shareable Certificate,Approx. 40 hours to complete,English,NaN,free,4.7,2022-07-30T00:02:16Z,2022-07-30 00:02:16+00:00
19,https://www.coursera.org/learn/uvaNAdardenNAag...,Agile Analytics,University of Virginia,course,Design and Product,Shareable Certificate,Approx. 15 hours to complete,English,Beginner Level,free,4.7,2022-07-30T00:02:59Z,2022-07-30 00:02:59+00:00
20,https://www.coursera.org/learn/buildingNAaiNAp...,Building AI Powered Chatbots Without Programming,IBM Skills Network,course,Design and Product,Shareable Certificate,Approx. 11 hours to complete,English,Beginner Level,free,4.8,2022-07-30T00:03:00Z,2022-07-30 00:03:00+00:00
21,https://www.coursera.org/specializations/realN...,RealNAWorld Product Management Specialization,Advancing Women in Tech,specializations,Design and Product,Shareable Certificate,Approximately 4 months to complete,English,Beginner Level,free,4.6,2022-07-30T00:03:42Z,2022-07-30 00:03:42+00:00
22,https://www.coursera.org/specializations/michi...,User Experience Research and Design Specializa...,University of Michigan,specializations,Design and Product,Shareable Certificate,Approximately 9 months to complete,English,Beginner Level,free,4.8,2022-07-30T00:03:42Z,2022-07-30 00:03:42+00:00
23,https://www.coursera.org/learn/clientNAneedsNA...,Client Needs and Software Requirements,University of Alberta,course,Design and Product,Shareable Certificate,Approx. 12 hours to complete,English,NaN,free,4.8,2022-07-30T00:03:42Z,2022-07-30 00:03:42+00:00
24,https://www.coursera.org/learn/uiNAtesting,Evaluating User Interfaces,University of Minnesota,course,Design and Product,Shareable Certificate,Approx. 12 hours to complete,English,NaN,free,4.7,2022-07-30T00:04:11Z,2022-07-30 00:04:11+00:00
25,https://www.coursera.org/learn/uiNAdesign,Introduction to UI Design,University of Minnesota,course,Design and Product,Shareable Certificate,Approx. 14 hours to complete,English,Beginner Level,free,4.7,2022-07-30T00:04:11Z,2022-07-30 00:04:11+00:00
26,https://www.coursera.org/specializations/inter...,Interaction Design Specialization,University of California San Diego,specializations,Design and Product,Shareable Certificate,Approximately 10 months to complete,English,Intermediate Level,free,4.5,2022-07-30T00:04:11Z,2022-07-30 00:04:11+00:00
28,https://www.coursera.org/specializations/compu...,Fundamentals of Computer Network Security Spec...,University of Colorado System,specializations,Computer Security and Networks,Shareable Certificate,Approximately 4 months to complete,English,Intermediate Level,free,4.0,2022-07-30T00:04:50Z,2022-07-30 00:04:50+00:00
29,https://www.coursera.org/learn/introductionNAt...,Introduction to Networking and Storage,IBM Skills Network,course,Networking,Shareable Certificate,Approx. 7 hours to complete,English,Beginner Level,free,4.8,2022-07-30T00:04:50Z,2022-07-30 00:04:50+00:00
38,https://www.coursera.org/learn/networkingNAgcp...,Networking in Google Cloud: Defining and Imple...,Google Cloud,course,Networking,Shareable Certificate,Approx. 9 hours to complete,English,Intermediate Level,Enroll,4.8,2022-07-30T00:06:38Z,2022-07-30 00:06:38+00:00
39,https://www.coursera.org/learn/redesNAinformat...,Los bits y bytes de las redes informáticas,Google,course,Networking,Shareable Certificate,Approx. 25 hours to complete,Spanish,Beginner Level,free,4.8,2022-07-30T00:06:38Z,2022-07-30 00:06:38+00:00
40,https://www.coursera.org/learn/redesNAcomputad...,Estrutura e Funcionamento das Redes de Computa...,Google,course,Networking,Shareable Certificate,Approx. 25 hours to complete,Portuguese (Brazilian),Beginner Level,free,4.8,2022-07-30T00:07:05Z,2022-07-30 00:07:05+00:00
41,https://www.coursera.org/learn/selukNAbelukNAj...,Seluk Beluk Jaringan Komputer,Google,course,Networking,Shareable Certificate,Approx. 34 hours to complete,Indonesian,Beginner Level,free,4.9,2022-07-30T00:07:18Z,2022-07-30 00:07:18+00:00
45,https://www.coursera.org/specializations/netwo...,Networking in Google Cloud Specialization,Google Cloud,specializations,Networking,Shareable Certificate,Approximately 4 months to complete,English,Intermediate Level,free,4.8,2022-07-30T00:07:58Z,2022-07-30 00:07:58+00:00
46,https://www.coursera.org/learn/awsNAcloudNAtec...,AWS Cloud Technical Essentials,Amazon Web Services,course,Cloud Computing,Shareable Certificate,Approx. 14 hours to complete,English,Beginner Level,free,4.8,2022-07-30T00:07:58Z,2022-07-30 00:07:58+00:00
47,https://www.coursera.org/specializations/ibmNA...,Cloud Application Development Foundations Spec...,IBM Skills Network,specializations,Cloud Computing,Shareable Certificate,Approximately 6 months to complete,English,Beginner Level,free,4.6,2022-07-30T00:08:20Z,2022-07-30 00:08:20+00:00
48,https://www.coursera.org/learn/computerNAnetwo...,The Bits and Bytes of Computer Networking,Google,course,Networking,Shareable Certificate,Approx. 25 hours to complete,English,Beginner Level,free,4.7,2022-07-30T00:08:59Z,2022-07-30 00:08:59+00:00
49,https://www.coursera.org/learn/siteNAreliabili...,Site Reliability Engineering: Measuring and Ma...,Google Cloud,course,Cloud Computing,Shareable Certificate,Approx. 14 hours to complete,English,Intermediate Level,free,4.5,2022-07-30T00:08:59Z,2022-07-30 00:08:59+00:00
50,https://www.coursera.org/learn/uvaNAdardenNAco...,Continuous Delivery & DevOps,University of Virginia,course,Software Development,Shareable Certificate,Approx. 8 hours to complete,English,Beginner Level,free,4.6,2022-07-30T00:08:59Z,2022-07-30 00:08:59+00:00
51,https://www.coursera.org/learn/introductionNAt...,Introduction to Hardware and Operating Systems,IBM Skills Network,course,Support and Operations,Shareable Certificate,Approx. 11 hours to complete,English,Beginner Level,free,4.8,2022-07-30T00:09:29Z,2022-07-30 00:09:29+00:00
52,https://www.coursera.org/professionalNAcertifi...,IT Support Google Professional Certificate,Google,professional certificates,Support and Operations,Shareable Certificate,Approximately 6 months to complete,Indonesian,Beginner Level,free,4.9,2022-07-30T00:09:29Z,2022-07-30 00:09:29+00:00
54,https://www.coursera.org/learn/dasarNAdasarNAd...,DasarNADasar Dukungan Teknis,Google,course,Support and Operations,Shareable Certificate,Approx. 24 hours to complete,Indonesian,Beginner Level,free,4.9,2022-07-30T00:10:04Z,2022-07-30 00:10:04+00:00
55,https://www.coursera.org/learn/fundamentosNAdo...,Fundamentos do Suporte Técnico,Google,course,Support and Operations,Shareable Certificate,Approx. 23 hours to complete,Portuguese (Brazilian),Beginner Level,free,4.9,2022-07-30T00:10:04Z,2022-07-30 00:10:04+00:00
56,https://www.coursera.org/professionalNAcertifi...,Palo Alto Networks Cybersecurity Professional ...,Palo Alto Networks,professional certificates,Security,Shareable Certificate,Approximately 6 months to complete,English,Beginner Level,free,4.7,2022-07-30T00:10:04Z,2022-07-30 00:10:04+00:00
57,https://www.coursera.org/learn/oraclecloudNAin...,Oracle Cloud Infrastructure Foundations,Oracle,course,Cloud Computing,Shareable Certificate,Approx. 14 hours to complete,English,NaN,free,4.7,2022-07-30T00:10:33Z,2022-07-30 00:10:33+00:00
58,https://www.coursera.org/specializations/ijaut,Juniper Networks Junos Platform Automation and...,Juniper Networks,specializations,Cloud Computing,Shareable Certificate,Approximately 1 month to complete,English,Beginner Level,free,4.0,2022-07-30T00:10:33Z,2022-07-30 00:10:33+00:00
59,https://www.coursera.org/professionalNAcertifi...,IBM Technical Support Professional Certificate,IBM Skills Network,professional certificates,Support and Operations,Shareable Certificate,Approximately 8 months to complete,English,Beginner Level,free,4.7,2022-07-30T00:10:33Z,2022-07-30 00:10:33+00:00
62,https://www.coursera.org/professionalNAcertifi...,IBM DevOps and Software Engineering Profession...,IBM Skills Network,professional certificates,Software Development,Shareable Certificate,Approximately 12 months to complete,English,Beginner Level,free,4.7,2022-07-30T00:10:53Z,2022-07-30 00:10:53+00:00
64,https://www.coursera.org/learn/pythonNAcrashNA...,Crash Course on Python,Google,course,Support and Operations,Shareable Certificate,Approx. 28 hours to complete,English,Beginner Level,free,4.8,2022-07-30T00:11:27Z,2022-07-30 00:11:27+00:00
66,https://www.coursera.org/learn/technicalNAsupp...,Technical Support Fundamentals,Google,course,Support and Operations,Shareable Certificate,Approx. 20 hours to complete,English,Beginner Level,free,4.8,2022-07-30T00:11:48Z,2022-07-30 00:11:48+00:00
68,https://www.coursera.org/learn/enterpriseNAsys...,Enterprise System Management and Security,University of Colorado System,course,Security,Shareable Certificate,Approx. 12 hours to complete,English,Beginner Level,free,4.7,2022-07-30T00:11:48Z,2022-07-30 00:11:48+00:00
69,https://www.coursera.org/learn/customerNAservi...,Customer Service Fundamentals,Knowledge Accelerators,course,Support and Operations,Shareable Certificate,Approx. 24 hours to complete,English,Beginner Level,Enroll,4.8,2022-07-30T00:12:07Z,2022-07-30 00:12:07+00:00
70,https://www.coursera.org/learn/pythonNAoperati...,Using Python to Interact with the Operating Sy...,Google,course,Support and Operations,Shareable Certificate,Approx. 27 hours to complete,English,Beginner Level,free,4.7,2022-07-30T00:12:17Z,2022-07-30 00:12:17+00:00

Inconsistencies: (view in excel)
- Google/Google Cloud > Google
- IBM Skills Network > IBM
- Georgia Institute of Technology + University System of Georgia
- Group together states w/ more than one college listed

In [40]:
california = ['California Institute of the Arts', 'Stanford University', 'University of California, Irvine', 'University of California, Davis']
michigan = ['University of Michigan', 'Michigan State University']

df_renamed['institution'] = np.where(df_renamed['institution'] == 'Google Cloud', 'Google', df_renamed['institution'])
df_renamed['institution'] = np.where(df_renamed['institution'] == 'IBM Skills Network', 'IBM', df_renamed['institution'])
df_renamed['institution'] = np.where(df_renamed['institution'] == 'Georgia Institute of Technology', 'University System of Georgia', df_renamed['institution'])

for y in michigan:
    df_renamed['institution'] = np.where(df_renamed['institution'] == y, 'University System of Michigan', df_renamed['institution'])

for x in california:
    df_renamed['institution'] = np.where(df_renamed['institution'] == x, 'University System of California', df_renamed['institution'])

df_renamed['institution'].value_counts()

Google                                                37
IBM                                                   14
University System of Michigan                          8
University System of California                        8
University of Colorado System                          7
University of Virginia                                 6
Macquarie University                                   6
University of Pennsylvania                             6
The Hong Kong University of Science and Technology     5
University of Colorado Boulder                         4
Duke University                                        4
University of Toronto                                  3
Meta                                                   3
University of Alberta                                  3
University of Minnesota                                3
University of California San Diego                     3
DeepLearning.AI                                        2
University System of Georgia                           2
Princeton University                                   2
University of Arizona                                  2
Amazon Web Services                                    2
University of Geneva                                   1
Universidade de São Paulo                              1
Politecnico di Milano                                  1
LudwigNAMaximiliansNAUniversität München (LMU)         1
The University of Sydney                               1
Rutgers the State University of New Jersey             1
University of Maryland, College Park                   1
University of Kentucky                                 1
Technical University of Denmark (DTU)                  1
McMaster University                                    1
École Polytechnique                                    1
University of Amsterdam                                1
CentraleSupélec                                        1
Pontificia Universidad Católica de Chile               1
GitLab                                                 1
Alibaba Cloud Academy                                  1
Universidad Austral                                    1
Imperial College London                                1
Universidad de los Andes                               1
(ISC)²                                                 1
New York University                                    1
Knowledge Accelerators                                 1
Juniper Networks                                       1
Oracle                                                 1
Palo Alto Networks                                     1
Advancing Women in Tech                                1
University of Manchester                               1
Name: institution, dtype: int64

**9. Check the column 'rating'. Are there any outliers? The value for rating shall be between 0 and 5. If there are outliers, remove these rows. 5 points**

In [41]:
outlier_ratings = df_renamed.loc[(df_renamed['rating'] >= 0)&(df_renamed['rating'] <= 5)] 
outlier_ratings

,url,title,institution,type,category-subject-area,certificate-is-available,duration,language,level,price,rating,timestamp,timestamp_dt
1,https://www.coursera.org/learn/2NAspeedNAit,Two Speed IT: How Companies Can Surf the Digit...,CentraleSupélec,course,Business Essentials,Shareable Certificate,Approx. 14 hours to complete,English,NaN,free,4.3,2022-07-29T23:58:34Z,2022-07-29 23:58:34+00:00
2,https://www.coursera.org/learn/fundamentalsNAn...,Fundamentals of Network Communication,University of Colorado System,course,Computer Security and Networks,Shareable Certificate,Approx. 15 hours to complete,English,Intermediate Level,free,4.6,2022-07-29T23:58:54Z,2022-07-29 23:58:54+00:00
3,https://www.coursera.org/learn/uxNAdesignNAjobs,Design a User Experience for Social Good & Pre...,Google,course,Design and Product,Shareable Certificate,Approx. 71 hours to complete,English,Beginner Level,free,4.8,2022-07-29T23:59:20Z,2022-07-29 23:59:20+00:00
4,https://www.coursera.org/learn/databaseNAappli...,Building Database Applications in PHP,University System of Michigan,course,Mobile and Web Development,Shareable Certificate,Approx. 24 hours to complete,English,Intermediate Level,free,4.9,2022-07-29T23:59:20Z,2022-07-29 23:59:20+00:00
5,https://www.coursera.org/learn/webNAdesignNAwi...,Web Design: Wireframes to Prototypes,University System of California,course,Music and Art,Shareable Certificate,Approx. 41 hours to complete,English,Intermediate Level,free,4.9,2022-07-29T23:59:20Z,2022-07-29 23:59:20+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,https://www.coursera.org/specializations/dataN...,Data Science: Foundations using R Specialization,NaN,specializations,Data Analysis,Shareable Certificate,Approximately 5 months to complete,English,Beginner Level,free,4.6,2022-07-30T00:45:32Z,2022-07-30 00:45:32+00:00
235,https://www.coursera.org/professionalNAcertifi...,IBM Data Science Professional Certificate,IBM,professional certificates,Data Analysis,Shareable Certificate,Approximately 11 months to complete,English,Beginner Level,free,4.6,2022-07-30T00:45:32Z,2022-07-30 00:45:32+00:00
239,https://www.coursera.org/specializations/jhuNA...,Data Science Specialization,NaN,specializations,Data Analysis,Shareable Certificate,Approximately 11 months to complete,English,Beginner Level,free,4.5,2022-07-30T00:45:32Z,2022-07-30 00:45:32+00:00
240,https://www.coursera.org/learn/physicalNAchemi...,Introduction to Physical Chemistry,University of Manchester,course,Chemistry,Shareable Certificate,Approx. 19 hours to complete,English,NaN,free,4.7,2022-07-30T00:45:41Z,2022-07-30 00:45:41+00:00
241,https://www.coursera.org/learn/basicNAchemistry,Introduction to Chemistry: Structures and Sol...,Duke University,course,Chemistry,Shareable Certificate,Approx. 17 hours to complete,English,Beginner Level,free,4.7,2022-07-30T00:45:42Z,2022-07-30 00:45:42+00:00

**10. Use groupby or pivot table to show the average rating score for each institution. Which are the top 5 institutions that have the highest average rating scores? 10 points**

In [42]:
pd.pivot_table(outlier_ratings, values=None, columns='institution', aggfunc='mean', dropna=True, sort=True)

institution,(ISC)²,Advancing Women in Tech,Alibaba Cloud Academy,Amazon Web Services,CentraleSupélec,DeepLearning.AI,Duke University,GitLab,Google,IBM,...,University of Colorado System,University of Geneva,University of Kentucky,University of Manchester,"University of Maryland, College Park",University of Minnesota,University of Pennsylvania,University of Toronto,University of Virginia,École Polytechnique
rating,4.8,4.6,4.4,4.75,4.3,4.65,4.65,4.8,4.797297,4.671429,...,4.557143,4.2,4.7,4.7,4.6,4.733333,4.75,4.833333,4.716667,4.8

Top 5 institution ratings:
1. (ISC)^2
2. Advancing Women in Tech
3. Alibaba Cloud Academy
4. Amazon Web Services
5. CentraleSupelec

**11. Use groupby or pivot table to show the number of courses offered by each institution. Which are the top 5 institutions that offer the most courses? 10 points**

In [44]:
pd.pivot_table(outlier_ratings, values=None, index='institution', aggfunc='count', dropna=True, sort=True)

,category-subject-area,certificate-is-available,duration,language,level,price,rating,timestamp,timestamp_dt,title,type,url
institution,,,,,,,,,,,,
(ISC)²,1,1,1,1,1,1,1,1,1,1,1,1
Advancing Women in Tech,1,1,1,1,1,1,1,1,1,1,1,1
Alibaba Cloud Academy,1,1,1,1,1,1,1,1,1,1,1,1
Amazon Web Services,2,2,2,2,2,2,2,2,2,2,2,2
CentraleSupélec,1,1,1,1,0,1,1,1,1,1,1,1
DeepLearning.AI,2,2,2,2,2,2,2,2,2,2,2,2
Duke University,4,4,4,4,4,4,4,4,4,4,4,4
GitLab,1,1,1,1,1,1,1,1,1,1,1,1
Google,37,37,37,37,37,37,37,37,37,37,37,37
IBM,14,14,14,14,14,14,14,14,14,14,14,14
Imperial College London,1,1,1,1,1,1,1,1,1,1,1,1
Juniper Networks,1,1,1,1,1,1,1,1,1,1,1,1
Knowledge Accelerators,1,1,1,1,1,1,1,1,1,1,1,1
Macquarie University,6,6,6,6,4,6,6,6,6,6,6,6
McMaster University,1,1,1,1,1,1,1,1,1,1,1,1
Meta,3,3,3,3,3,3,3,3,3,3,3,3
New York University,1,1,1,1,1,1,1,1,1,1,1,1
Oracle,1,1,1,1,0,1,1,1,1,1,1,1
Palo Alto Networks,1,1,1,1,1,1,1,1,1,1,1,1
Politecnico di Milano,1,1,1,1,1,1,1,1,1,1,1,1
Pontificia Universidad Católica de Chile,1,1,1,1,1,1,1,1,1,1,1,1
Princeton University,2,0,2,2,0,2,2,2,2,2,2,2
Rutgers the State University of New Jersey,1,1,1,1,1,1,1,1,1,1,1,1
Technical University of Denmark (DTU),1,1,1,1,0,1,1,1,1,1,1,1
The Hong Kong University of Science and Technology,5,5,5,5,5,5,5,5,5,5,5,5
The University of Sydney,1,1,1,1,1,1,1,1,1,1,1,1
Universidad Austral,1,1,1,1,1,1,1,1,1,1,1,1
Universidad de los Andes,1,1,1,1,1,1,1,1,1,1,1,1
Universidade de São Paulo,1,1,1,1,1,1,1,1,1,1,1,1
University System of California,6,6,6,6,5,6,6,6,6,6,6,6
University System of Georgia,1,1,1,1,1,1,1,1,1,1,1,1
University System of Michigan,8,8,8,8,6,8,8,8,8,8,8,8
University of Alberta,3,3,3,3,1,3,3,3,3,3,3,3
University of Amsterdam,1,1,1,1,0,1,1,1,1,1,1,1
University of Arizona,2,2,2,2,2,2,2,2,2,2,2,2
University of California San Diego,3,3,3,3,3,3,3,3,3,3,3,3
University of Colorado Boulder,4,4,4,4,4,4,4,4,4,4,4,4
University of Colorado System,7,7,7,7,7,7,7,7,7,7,7,7
University of Geneva,1,1,1,1,0,1,1,1,1,1,1,1
University of Kentucky,1,0,1,1,0,1,1,1,1,1,1,1
University of Manchester,1,1,1,1,0,1,1,1,1,1,1,1
"University of Maryland, College Park",1,1,1,1,1,1,1,1,1,1,1,1
University of Minnesota,3,3,3,3,2,3,3,3,3,3,3,3
University of Pennsylvania,6,5,6,6,0,6,6,6,6,6,6,6
University of Toronto,3,3,3,3,3,3,3,3,3,3,3,3
University of Virginia,6,6,6,6,5,6,6,6,6,6,6,6
École Polytechnique,1,1,1,1,0,1,1,1,1,1,1,1

Top 5 institutions that offer the most courses:
1. Google
2. IBM
3. University System of Michigan
4. University of Colorado System
5. Macquarie University

**12. Use a pivot table to show how many courses at different levels each institution offer. Which institution offer the most advanced-level courses? Which institution offer the most intermediate-level courses? Which institution offer the most beginner-level courses? 10 points**

In [50]:
pd.pivot_table(outlier_ratings, values=None, index='level', columns='institution', aggfunc='count', dropna=True, sort=True)

                   category-subject-area                          \
institution                       (ISC)² Advancing Women in Tech
level
Advanced Level                       NaN                     NaN
Beginner Level                       1.0                     1.0
Intermediate Level                   NaN                     NaN

                                                                              \
institution        Alibaba Cloud Academy Amazon Web Services DeepLearning.AI
level
Advanced Level                       NaN                 NaN             1.0
Beginner Level                       NaN                 1.0             NaN
Intermediate Level                   1.0                 1.0             1.0

                                                        \
institution        Duke University GitLab Google   IBM
level
Advanced Level                 NaN    NaN    NaN   NaN
Beginner Level                 4.0    NaN   28.0  14.0
Intermediate Level             NaN    1.0    9.0   NaN

                                            ...                           url  \
institution        Imperial College London  ... University System of Michigan
level                                       ...
Advanced Level                         NaN  ...                           NaN
Beginner Level                         1.0  ...                           4.0
Intermediate Level                     NaN  ...                           2.0

                                                                \
institution        University of Alberta University of Arizona
level
Advanced Level                       NaN                   NaN
Beginner Level                       1.0                   2.0
Intermediate Level                   NaN                   NaN

                                                       \
institution        University of California San Diego
level
Advanced Level                                    NaN
Beginner Level                                    NaN
Intermediate Level                                3.0

                                                   \
institution        University of Colorado Boulder
level
Advanced Level                                2.0
Beginner Level                                1.0
Intermediate Level                            1.0

                                                  \
institution        University of Colorado System
level
Advanced Level                               NaN
Beginner Level                               4.0
Intermediate Level                           3.0

                                                         \
institution        University of Maryland, College Park
level
Advanced Level                                      NaN
Beginner Level                                      NaN
Intermediate Level                                  1.0

                                                                  \
institution        University of Minnesota University of Toronto
level
Advanced Level                         NaN                   NaN
Beginner Level                         2.0                   3.0
Intermediate Level                     NaN                   NaN


institution        University of Virginia
level
Advanced Level                        NaN
Beginner Level                        4.0
Intermediate Level                    1.0

[3 rows x 407 columns]

- **Most advanced level**: University of Colorado Boulder
- **Most intermediate level**: University of California San Diego
- **Most beginner level**: Duke University

THIS IS AN INDIVIDUAL ASSIGNMENT. YOU MAY NOT DISCUSS THIS ASSIGNMENT WITH ANYONE WITHIN OR OUTSIDE THE CLASS (except the instructor).
- DO not discuss your approaches or your code with colleagues. There are many ways to implement this assignment, and it is extremely easy to spot code that has been inspired by someone else’s code and to identify unauthorized collaborations.
- If you choose to utilize something you find online, cite that resource, but DO NOT share that resource with anyone else.
By submitting this assignment, you certify that no unauthorized assistance has been received or given in the completion of this work.
- McKenzie Church